import { useEffect, useMemo, useRef, useState } from "react";
import {
  Accessibility,
  AlertTriangle,
  Bell,
  Car,
  Check,
  ChevronRight,
  ClipboardList,
  Clock3,
  Copy,
  Fingerprint,
  Flame,
  Gavel,
  Hand,
  HeartHandshake,
  Home,
  Info,
  Landmark,
  LifeBuoy,
  Loader2,
  MapPin,
  Menu,
  Mic,
  MicOff,
  Moon,
  Phone,
  Scale,
  Search,
  Share2,
  Shield,
  ShieldAlert,
  ShoppingBag,
  Siren,
  Star,
  Stethoscope,
  Sun,
  Users,
  Wifi,
  X,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import "./styles.css";

const services = [
  {
    id: "policia",
    name: "Polícia",
    number: "190",
    description: "Emergências policiais, crimes em andamento e situações de risco.",
    icon: ShieldAlert,
    category: "Segurança",
    keywords: [
      "policia",
      "polícia",
      "assalto",
      "roubo",
      "furto",
      "crime",
      "bandido",
      "arma",
      "violencia",
      "violência",
      "briga",
      "agressao",
      "agressão",
      "perigo",
    ],
  },
  {
    id: "bombeiros",
    name: "Bombeiros",
    number: "193",
    description: "Incêndios, acidentes, resgates e situações de emergência.",
    icon: Flame,
    category: "Emergência",
    keywords: [
      "incendio",
      "incêndio",
      "fogo",
      "acidente",
      "resgate",
      "explosao",
      "explosão",
      "desabamento",
      "pessoa presa",
      "enchente",
    ],
  },
  {
    id: "samu",
    name: "SAMU",
    number: "192",
    description: "Atendimento médico de urgência e emergência.",
    icon: Stethoscope,
    category: "Saúde",
    keywords: [
      "samu",
      "medico",
      "médico",
      "hospital",
      "ambulancia",
      "ambulância",
      "passou mal",
      "desmaio",
      "desmaiou",
      "infarto",
      "dor",
      "ferido",
      "ferida",
      "acidente",
      "socorro",
      "emergencia",
      "emergência",
    ],
  },
  {
    id: "conselho",
    name: "Conselho Tutelar",
    number: "100",
    description: "Denúncias e proteção de crianças e adolescentes.",
    icon: Users,
    category: "Proteção",
    keywords: [
      "crianca",
      "criança",
      "adolescente",
      "menor",
      "maus tratos",
      "maus-tratos",
      "abandono infantil",
      "abuso infantil",
    ],
  },
  {
    id: "defesa-civil",
    name: "Defesa Civil",
    number: "199",
    description: "Alagamentos, enchentes, deslizamentos e riscos estruturais.",
    icon: AlertTriangle,
    category: "Emergência",
    keywords: [
      "alagamento",
      "alagada",
      "alagado",
      "enchente",
      "enchendo",
      "deslizamento",
      "desmoronamento",
      "desabamento",
      "chuva",
      "inund